name: Test-gofmt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        go: ["1.13", "1.14"]
    
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v2
    - name: Check go fmt
      run: gofmt -d -s -e */*.go

