name: TestGoTools

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go: ["1.19", "1.20"]

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check gofmt
      run: |
        output=$(gofmt -d -s -e -l .)
        if test -z "$output"; then
          echo "All files are already gofmt"
          exit 0;
        else
          echo "$output"
          exit 1;
        fi

    - name: Check golint
      run: |
        go install golang.org/x/lint/golint@latest
        output=$(golint ./...)
        if test -z "$output"; then
          echo "All files are already golint"
          exit 0;
        else
          echo "$output"
          exit 1;
        fi

    - name: Check ineffassign
      run: |
        go install github.com/gordonklaus/ineffassign@latest
        GO111MODULE=off ineffassign ./...
